version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
        - SECRET_KEY=fdkwoqnwreq-rgn93g38t20tghrnr3gh08b2ntg402hth
        - DATABASE_ENGINE=django.db.backends.postgresql
        - DATABASE_NAME=postgres
        - DATABASE_USER=postgres
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - ALLOWED_HOSTS=localhost
        - DEBUG=True
    ports:
      - "8000:8000"
