# Generated by Django 3.0.2 on 2020-02-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_short',
            field=models.TextField(default=''),
        ),
    ]
