# Generated by Django 3.0.3 on 2020-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0002_post_content_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_short',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
