# Generated by Django 3.0.3 on 2020-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0003_auto_20200217_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
