# Generated by Django 3.0.3 on 2020-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0005_auto_20200218_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('posts', models.ManyToManyField(to='blogging_api.Post')),
            ],
        ),
    ]
