# Generated by Django 3.0.3 on 2020-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0007_auto_20200219_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_to_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
