# Generated by Django 3.0.3 on 2020-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='homepage_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='infopage_content',
            field=models.BooleanField(default=False),
        ),
    ]
