# Generated by Django 3.0.3 on 2020-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_api', '0010_auto_20200222_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='backend_tag',
            field=models.BooleanField(default=False),
        ),
    ]
